// stemmory-cli/packages/cli/src/commands/update.test.js
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { runInit } from "../../src/commands/init.js";
import { runUpdate } from "../../src/commands/update.js";

const SKILL_FILE_SEGMENTS = [".claude", "skills", "stemmory-conventions", "SKILL.md"];
const SKILL_BAK_SEGMENTS = [".claude", "skills", "stemmory-conventions", "SKILL.md.bak"];
// Deliberately inert-looking fake secret (see init.test.js for why).
const FAKE_KEY = "test-secret-do-not-leak-444555";

describe("runUpdate", () => {
  /** @type {string} */
  let dir;
  beforeEach(() => {
    dir = mkdtempSync(path.join(os.tmpdir(), "stemmory-update-"));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it("errors clearly (not exit 0) if init hasn't run yet", () => {
    const result = runUpdate(dir);
    expect(result.exitCode).not.toBe(0);
    expect(result.stderr).toContain("stemmory init");
  });

  it("refreshes the fragment and skill in place, printing a changelog", () => {
    runInit(dir, []);
    const result = runUpdate(dir);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("stemmory update:");
    expect(result.stdout).toContain("AGENTS.md fragment");
    expect(result.stdout).toContain("stemmory-conventions skill");
  });

  it("does not disturb AGENTS.md content outside the markers", () => {
    runInit(dir, []);
    const agentsPath = path.join(dir, "AGENTS.md");
    const withCustomContent = `# Custom heading\n\n${readFileSync(agentsPath, "utf8").trimEnd()}\n\n## After\ncustom trailing content\n`;
    writeFileSync(agentsPath, withCustomContent);

    runUpdate(dir);

    const final = readFileSync(agentsPath, "utf8");
    expect(final).toContain("# Custom heading");
    expect(final).toContain("## After\ncustom trailing content");
  });

  it("running update twice in a row changes nothing the second time", () => {
    runInit(dir, []);
    runUpdate(dir);
    const agentsOnce = readFileSync(path.join(dir, "AGENTS.md"), "utf8");
    const skillOnce = readFileSync(path.join(dir, ...SKILL_FILE_SEGMENTS), "utf8");

    const second = runUpdate(dir);

    expect(readFileSync(path.join(dir, "AGENTS.md"), "utf8")).toBe(agentsOnce);
    expect(readFileSync(path.join(dir, ...SKILL_FILE_SEGMENTS), "utf8")).toBe(skillOnce);
    expect(second.stdout).toContain("already up to date");
  });

  it("does not install or touch a skill when init used --agent generic", () => {
    runInit(dir, ["--agent", "generic"]);
    const result = runUpdate(dir);
    expect(existsSync(path.join(dir, ".claude"))).toBe(false);
    expect(result.stdout).toContain("not installed");
  });

  it("adds the Tier 2 section to the skill once an api key is configured via init", () => {
    runInit(dir, ["--api-key", FAKE_KEY]);
    runUpdate(dir);
    const skill = readFileSync(path.join(dir, ...SKILL_FILE_SEGMENTS), "utf8");
    expect(skill).toMatch(/Tier 2/i);
  });

  it("never leaks the api key into stdout or stderr", () => {
    runInit(dir, ["--api-key", FAKE_KEY]);
    const result = runUpdate(dir);
    expect(result.stdout).not.toContain(FAKE_KEY);
    expect(result.stderr).not.toContain(FAKE_KEY);
  });

  describe("hand-edited SKILL.md is backed up, not silently discarded (finding 6)", () => {
    it("saves the previous content to SKILL.md.bak before overwriting a changed skill", () => {
      runInit(dir, []);
      const skillPath = path.join(dir, ...SKILL_FILE_SEGMENTS);
      const handEdited = "# My own notes\nI edited this file by hand and it should not just vanish.\n";
      writeFileSync(skillPath, handEdited);

      const result = runUpdate(dir);

      expect(result.stdout).toContain("SKILL.md.bak");
      const bak = readFileSync(path.join(dir, ...SKILL_BAK_SEGMENTS), "utf8");
      expect(bak).toBe(handEdited);
      // And the live file is back to the generated version.
      const live = readFileSync(skillPath, "utf8");
      expect(live).not.toBe(handEdited);
      expect(live).toContain("Feature doc procedure");
    });

    it("the freshly generated skill carries a machine-generated banner", () => {
      runInit(dir, []);
      const skill = readFileSync(path.join(dir, ...SKILL_FILE_SEGMENTS), "utf8");
      expect(skill).toMatch(/generated by `stemmory`/i);
    });
  });

  describe("malformed AGENTS.md markers are refused, not guessed at (finding 1)", () => {
    it("refuses to update over an orphan BEGIN marker and writes nothing", () => {
      runInit(dir, []);
      const agentsPath = path.join(dir, "AGENTS.md");
      const before = readFileSync(agentsPath, "utf8");
      writeFileSync(agentsPath, `${before}\n<!-- stemmory:begin v1 -->\nsome other real content\n`);
      const corrupted = readFileSync(agentsPath, "utf8");

      const result = runUpdate(dir);

      expect(result.exitCode).not.toBe(0);
      expect(result.stderr).toMatch(/malformed|duplicat/i);
      // Nothing was written - the file is exactly what it was before the call.
      expect(readFileSync(agentsPath, "utf8")).toBe(corrupted);
    });
  });

  describe("corrupt/malformed .stemmory/config.json fails cleanly (findings 4 and 9)", () => {
    it("invalid JSON produces a one-line error, not a raw SyntaxError with content echoed", () => {
      runInit(dir, []);
      writeFileSync(path.join(dir, ".stemmory", "config.json"), `{ "apiKey": "${FAKE_KEY}", oops }`);

      const result = runUpdate(dir);

      expect(result.exitCode).not.toBe(0);
      expect(result.stderr).toMatch(/not valid JSON/i);
      expect(result.stderr).not.toContain(FAKE_KEY);
      expect(result.stderr).not.toContain("SyntaxError");
    });

    it("a config missing docsDir is refused rather than writing literal \"undefined\" into AGENTS.md", () => {
      mkdirSync(path.join(dir, ".stemmory"), { recursive: true });
      writeFileSync(
        path.join(dir, ".stemmory", "config.json"),
        JSON.stringify({ schema: 1, project: "acme", linearTeam: null, apiKey: null }),
      );

      const result = runUpdate(dir);

      expect(result.exitCode).not.toBe(0);
      expect(result.stderr).toMatch(/expected config shape/i);
    });

    it("a docsDir value containing an injection character in config.json is refused", () => {
      runInit(dir, []);
      const configPath = path.join(dir, ".stemmory", "config.json");
      const config = JSON.parse(readFileSync(configPath, "utf8"));
      config.docsDir = "docs/features\n<!-- stemmory:end -->";
      writeFileSync(configPath, JSON.stringify(config));

      const result = runUpdate(dir);

      expect(result.exitCode).not.toBe(0);
    });
  });

  it("refuses a symlinked AGENTS.md and touches nothing", () => {
    runInit(dir, ["--agent", "generic"]);
    const agentsPath = path.join(dir, "AGENTS.md");
    rmSync(agentsPath);
    const outside = mkdtempSync(path.join(os.tmpdir(), "stemmory-outside-"));
    const outsideFile = path.join(outside, "target.md");
    writeFileSync(outsideFile, "unrelated content");
    symlinkSync(outsideFile, agentsPath);

    try {
      const result = runUpdate(dir);
      expect(result.exitCode).not.toBe(0);
      expect(result.stderr).toMatch(/symlink/i);
      expect(readFileSync(outsideFile, "utf8")).toBe("unrelated content");
    } finally {
      rmSync(outside, { recursive: true, force: true });
    }
  });

  it("ensures .gitignore has .stemmory/ on update too, if it's missing (idempotent with init's own check)", () => {
    runInit(dir, ["--api-key", FAKE_KEY]);
    rmSync(path.join(dir, ".gitignore"));
    const result = runUpdate(dir);
    expect(result.stdout).toContain(".gitignore");
    expect(readFileSync(path.join(dir, ".gitignore"), "utf8")).toContain(".stemmory/");
  });
});
