// stemmory-cli/packages/cli/src/lib/skill.js
//
// Generates the `stemmory-conventions` skill body (AGENT_CONVENTIONS_KIT_
// SPEC.md §2.2): six required sections - feature-doc procedure, decision
// record format, status transitions, the Linear labeling rule, the
// session-end ritual, and the Tier 2 extension, which is included only
// when the project's `.stemmory/config.json` carries an API key (§2.2
// point 6). Frontmatter field docs and the status vocabulary come from
// `@stemmory/schema` (skill-fields.js), not hand-typed here.
import { CURRENT_SCHEMA_VERSION, DOC_STATUS_VALUES, MAX_SLUG_DEPTH } from "@stemmory/schema";

import { frontmatterFieldTable } from "./skill-fields.js";

export const SKILL_NAME = "stemmory-conventions";

/**
 * @param {string} docsDir
 */
function frontmatterBlock(docsDir) {
  return `---
name: ${SKILL_NAME}
description: Use when creating or updating a feature, writing or editing docs
  in ${docsDir}/, recording a product or technical decision, creating Linear
  issues for feature work, or finishing a work session that changed what the
  project is building. Provides the Stemmory frontmatter schema, feature-doc
  and decision-record templates, and the Linear labeling rule so the
  project's living map stays accurate.
---`;
}

/** @param {string} docsDir */
function featureDocProcedure(docsDir) {
  return `## 1. Feature doc procedure
Create a new feature at \`${docsDir}/<slug>.md\`. \`<slug>\` is kebab-case path
segments joined by \`/\`, max depth ${MAX_SLUG_DEPTH}, and must match the filename.
Start the file with frontmatter (schema v${CURRENT_SCHEMA_VERSION}):

${frontmatterFieldTable()}

Never guess this schema by hand - the table above is generated straight from
\`@stemmory/schema\`, the same validator \`stemmory lint\` and hosted ingest
both run, so it cannot drift from what actually gets checked.`;
}

function decisionRecordFormat() {
  return `## 2. Decision record format
Record decisions in the doc's \`## Decisions\` section as one line each,
appended - never rewrite or delete an existing line:

\`- YYYY-MM-DD — Decision — Why — Alternatives considered\``;
}

function statusTransitions() {
  const values = DOC_STATUS_VALUES.map((s) => `\`${s}\``).join(", ");
  return `## 3. Status transitions
Allowed \`status\` values: ${values}. Changing a feature's status requires a
new dated line in \`## Decisions\` explaining why - a status change with no
recorded reason is a lint-visible smell even where the validator doesn't
hard-reject it.`;
}

function linearRule() {
  return `## 4. Linear rule
When creating a Linear issue for feature work (via the user's Linear MCP),
apply the label \`feature:<slug>\`. The slug must correspond to an existing
feature doc - create the doc first if it doesn't exist yet.`;
}

function sessionEndRitual() {
  return `## 5. Session-end ritual
Before finishing any work that changed a feature's scope or status: update
its doc in the same session, then run \`stemmory lint\` if the CLI is present
on this machine and fix any violations it reports.`;
}

function tier2Extension() {
  return `## 6. Tier 2 — Stemmory MCP write path
This project has a Stemmory API key configured (\`.stemmory/config.json\`).
After updating a feature doc, also push the corresponding node/edge updates
through the Stemmory MCP write tools, with provenance (who, what, when,
from which commit) on every write - the doc and the graph should never
disagree about what shipped.`;
}

/**
 * @param {{ docsDir: string, hasApiKey: boolean }} opts
 * @returns {string}
 */
export function buildSkillMarkdown({ docsDir, hasApiKey }) {
  const sections = [
    frontmatterBlock(docsDir),
    "# Stemmory conventions\n\n" +
      "> Generated by `stemmory`. `stemmory update` overwrites this file - a previous " +
      "version is saved to `SKILL.md.bak` first, but put project-specific notes in " +
      "`AGENTS.md` instead of editing this one directly.",
    featureDocProcedure(docsDir),
    decisionRecordFormat(),
    statusTransitions(),
    linearRule(),
    sessionEndRitual(),
  ];
  if (hasApiKey) sections.push(tier2Extension());
  return `${sections.join("\n\n")}\n`;
}
